CREATE TABLE IF NOT EXISTS roles
(
    role_id BIGSERIAL PRIMARY KEY,

    role_name VARCHAR(50) NOT NULL UNIQUE,

    description TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);